[build]
builder = "nixpacks"
buildCommand = "composer install && npm install && npm run build && php artisan storage:link && chmod -R 775 storage bootstrap/cache && touch database/database.sqlite && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 